# Table with genomes to use
genome_table: examples/data/genome_list.txt
# Abundace table
abund_table: example_wAbund.txt
# Table with specific genome's ancient properties
genome_comp: genome-comp.tsv
# Number of cpus. [Default: 1]
cpus: 16
# Minimum fragment length [Default: 30]
min-length: 30
# Fragment length distribution [Default: lognormal]
length-dist: lognormal
# Mode of the acient fragments length distribution [Default: 40]
mode-len-ancient: 40
# Mode of the acient fragments length distribution [Default: 100]
mode-len-modern: 100
# Proportion of ancient genomes per site. [Default: 0.1]
prop-ancient-comm: 0.2
# Maximum and minimum coverage of the ancient genomes in each samples. [Default: 0.1]
coverage: [0.1, 5]
# Sequencing technology [Default: HS25]
seqSys: HS25
# Number of reads to generate per sample [Default: 1e6]
num-reads: 5e6
# Desired final read length. Will be used by adptSim and ART [Default: 150]
read-len: 150
# Use single end library properties [Default: False]
library: paired
# Temporary folder
tmp_dir: .sim_reads-example
