global:
  # Path to the fragSim binary
  fragSim: fragSim
  # Path to the deamSim binary
  deamSim: deamSim
  # Path to the adptSim binary
  adptSim: adptSim
  # Path to the art_illumina binary
  art: art_illumina
  # Path to the AdapterRemoval binary
  AdapterRemoval: AdapterRemoval
  # Temporary folder
  tmp_dir: .sim_reads
  # Number of cpus
  cpus: 16
  # Output dir
  output_dir: example-data
  # libprep single or double
  libprep: double

fragSim:
  ancient_genomes: 0e59dd2155.json
  modern:
    --case: True # Do not set the sequence to upper-case (default: uppercase the seqs.)
    --comp: False # [file] Base composition for the fragments (default none)
    --dist: False # [file] Distance from ends to consider  (default: 1) if this is not specified, the base composition will only reflect the chromosome file used
    --norev: False # Do not reverse complement (default: rev. comp half of seqs.)
  ancient:
    --case: False # Do not set the sequence to upper-case (default: uppercase the seqs.)
    --comp: False # [file] Base composition for the fragments (default none)
    --dist: False # [file] Distance from ends to consider  (default: 1) if this is not specified, the base composition will only reflect the chromosome file used
    --norev: False # Do not reverse complement (default: rev. comp half of seqs.)
deamSim:
  -mapdamage: 0e59dd2155.woltka-mdmg.misincorporation.weight-0.txt.gz #  Read the miscorporation file [mis.txt] produced by metaDMG
  # v: nick frequency
  # l: length of overhanging ends (geometric parameter)
  # d: prob. of deamination of Cs in double-stranded parts
  # s: prob. of deamination of Cs in single-stranded parts
  -damage: False #[0.03, 0.1, 0.01, 0.1] #[0.03, 0.4, 0.01, 0.7] # For the Briggs et al. 2007 model The parameters must be comma-separated e.g.: -damage 0.03,0.4,0.01,0.7
adptSim:
  -f: AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATTCGATCTCGTATGC
  -s: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATTT
art:
  --qprof1: False
  --qprof2: False
# Experimental; not implemented yet
AdapterRemoval:
  --adapter1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATTCGATCTCGTATGC
  --adapter2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATTT
  --minlength: 30
  --trimns: True
  --collapse: True
  --trimqualities: True
  --minadapteroverlap: 1
  --preserve5p: False
  --minquality: 20
