# Table with genomes to use
genome-paths: genome-paths-list.tsv
names-dmp: names.dmp
nodes-dmp: nodes.dmp
acc2taxid: acc2taxid.map.gz
sample-name: "8bf92435d8"
# Abundace table
filterBAM-stats: 8bf92435d8.dedup_stats-filtered.tsv.gz
filterBAM-filter-conditions: { "breadth_exp_ratio": 0.75, "coverage_mean": 0 }
# Table with specific genome's ancient properties
use-restimated-proportions: True
# Table with specific genome's ancient properties
mdmg-results: 8bf92435d8.tp-mdmg.local.weight-1.csv.gz
mdmg-filter-conditions: { "damage": 0.1, "significance": 2 }
taxonomic-rank: "genus"
# Number of modern genomes
max-genomes-nondamaged: 10
# random, most_abundant, least_abundant
max-genomes-nondamaged-selection: "most_abundant"
# Number of ancient genomes
max-genomes-damaged-selection: "most_abundant"
max-genomes-damaged: 10
# Number of cpus. [Default: 1]
cpus: 16
# Which ranks we would like to keep
rank-filter-conditions:
  { "superkingdom": ["d__Bacteria", "d__Archaea", "d__Viruses"] }
